// app/relatorio/page.tsx
import { Card, Alert, Statistic } from 'antd';

import { usuarioAtual } from '../lib/demo.ts';
import { relatorioMensal } from '../lib/consultas.ts';
import { proveniencia } from '../lib/proveniencia.ts';
import { SeloCliente, SemCliente } from '../components/Selos.tsx';

export const dynamic = 'force-dynamic';

function brl(v: number, casas = 2): string {
  return v.toLocaleString('pt-BR', { minimumFractionDigits: casas, maximumFractionDigits: casas });
}

function mesExtenso(mes: string): string {
  const [ano, m] = mes.split('-');
  const nomes = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez'];
  return `${nomes[Number(m) - 1] ?? m}/${ano}`;
}

export default async function Pagina() {
  const u = await usuarioAtual();
  const [meses, proc] = await Promise.all([relatorioMensal(u), proveniencia(u)]);

  const totalLitros = meses.reduce((s, m) => s + m.litros, 0);
  const totalValor = meses.reduce((s, m) => s + m.valorTotal, 0);
  const totalExcedente = meses.reduce((s, m) => s + m.excedente, 0);
  const piorMes = [...meses].sort((a, b) => b.diferencaPercentual - a.diferencaPercentual)[0];
  const melhorMes = [...meses].sort((a, b) => a.diferencaPercentual - b.diferencaPercentual)[0];

  return (
    <>
      <div className="cabeca">
        <h1>Relatório mensal</h1>
        <p>A média da região é ponderada pelos seus litros, não a média simples das semanas.</p>
      </div>

      <div className="grade">
        <Card size="small">
          <Statistic title="Volume no período" value={`${brl(totalLitros, 0)} L`} valueStyle={{ fontSize: 24 }} />
        </Card>
        <Card size="small">
          <Statistic title="Gasto total" value={`R$ ${brl(totalValor)}`} valueStyle={{ fontSize: 24 }} />
        </Card>
        <Card size="small">
          <Statistic
            title={totalExcedente >= 0 ? 'Excedente sobre a média da região' : 'Economia sobre a média da região'}
            value={`R$ ${brl(Math.abs(totalExcedente))}`}
            valueStyle={{ fontSize: 24, color: totalExcedente >= 0 ? 'var(--sobe)' : 'var(--cai)' }}
          />
        </Card>
      </div>

      {piorMes !== undefined && melhorMes !== undefined && (
        <Alert
          type="info"
          showIcon
          style={{ marginBottom: 16 }}
          message="Leitura do período"
          description={
            <>
              Seu pior mês foi <strong>{mesExtenso(piorMes.mes)}</strong>, pagando{' '}
              {piorMes.diferencaPercentual.toFixed(1)}% em relação à média da região; o melhor foi{' '}
              <strong>{mesExtenso(melhorMes.mes)}</strong>, com{' '}
              {melhorMes.diferencaPercentual.toFixed(1)}%. A diferença entre os dois, aplicada ao
              volume do período, vale{' '}
              <strong>
                R$ {brl(((piorMes.diferencaPercentual - melhorMes.diferencaPercentual) / 100) *
                  (totalValor / totalLitros) * totalLitros)}
              </strong>
              .
            </>
          }
        />
      )}

      <Card
        size="small"
        title="Relatório mensal — preço pago versus média da região"
        extra={
          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 10 }}>
            <SeloCliente p={proc} />
            <a href="/relatorio/csv" download>
              Exportar CSV
            </a>
          </span>
        }
      >
        <table className="tabela-simples">
          <thead>
            <tr>
              <th>Mês</th>
              <th>Abastec.</th>
              <th>Litros</th>
              <th>Gasto (R$)</th>
              <th>Pago (R$/L)</th>
              <th>Região (R$/L)</th>
              <th>Diferença</th>
              <th>Excedente (R$)</th>
            </tr>
          </thead>
          <tbody>
            {meses.map((m) => (
              <tr key={m.mes}>
                <td style={{ textAlign: 'left' }}>{mesExtenso(m.mes)}</td>
                <td>{m.compras}</td>
                <td>{brl(m.litros, 0)}</td>
                <td>{brl(m.valorTotal)}</td>
                <td>{m.precoPago.toFixed(3)}</td>
                <td>{m.precoRegiao.toFixed(3)}</td>
                <td
                  style={{
                    color: m.diferencaPercentual > 0 ? 'var(--sobe)' : 'var(--cai)',
                    fontWeight: 600,
                  }}
                >
                  {m.diferencaPercentual > 0 ? '+' : ''}
                  {m.diferencaPercentual.toFixed(1)}%
                </td>
                <td>{brl(m.excedente)}</td>
              </tr>
            ))}
          </tbody>
        </table>
        {meses.length === 0 && <SemCliente oQue="O relatório mensal" />}
      </Card>

      <p className="rodape-nota">
        A comparação usa a média da região <strong>ponderada pelos seus litros</strong>, não a
        média simples das semanas. Sem isso, um mês em que o volume se concentra numa semana cara
        apareceria melhor do que foi.
      </p>
    </>
  );
}

// MVP-TCC/src/views/Relatorio.vue
<script setup lang="ts">
/**
 * Relatório mensal.
 *
 * A barra divergente com zero no centro é a forma certa aqui: o dado tem
 * POLARIDADE (acima ou abaixo da média), e barra empilhada a partir da esquerda
 * esconderia justamente o sinal.
 */
import { computed } from 'vue';
import Cabeca from '../components/Cabeca.vue';
import { atual } from '../lib/estado';
import { inteiro, mesBr, moeda, nf, pct } from '../lib/formato';

const d = computed(() => atual.value);

const maiorDif = computed(() =>
  Math.max(...d.value.relatorio.map((m) => Math.abs(m.diferencaPercentual)), 0.1),
);

const pior = computed(() =>
  [...d.value.relatorio].sort((a, b) => b.diferencaPercentual - a.diferencaPercentual)[0],
);
const melhor = computed(() =>
  [...d.value.relatorio].sort((a, b) => a.diferencaPercentual - b.diferencaPercentual)[0],
);

const totais = computed(() => {
  const r = d.value.relatorio;
  return {
    litros: r.reduce((s, m) => s + m.litros, 0),
    gasto: r.reduce((s, m) => s + m.valorTotal, 0),
    excedente: r.reduce((s, m) => s + m.excedente, 0),
  };
});

function csv(): void {
  const cab = 'mes;compras;litros;gasto;preco_pago;preco_regiao;diferenca_pct;excedente';
  const linhas = d.value.relatorio.map((m) =>
    [m.mes, m.compras, m.litros, m.valorTotal, m.precoPago, m.precoRegiao,
     m.diferencaPercentual.toFixed(2), m.excedente].join(';'),
  );
  const texto = `${cab}\n${linhas.join('\n')}\n`;
  const url = URL.createObjectURL(new Blob([texto], { type: 'text/csv;charset=utf-8' }));
  const a = document.createElement('a');
  a.href = url;
  a.download = 'relatorio-mensal-EXEMPLO.csv';
  a.click();
  URL.revokeObjectURL(url);
}
</script>

<template>
  <Cabeca titulo="Relatório mensal" sub="Preço pago versus média da região, mês a mês.">
    <template #acoes>
      <button class="btn" @click="csv">Exportar CSV</button>
    </template>
  </Cabeca>

  <div class="grade g-3 surge d1">
    <div class="cartao kpi">
      <span class="rot">Volume no período</span>
      <b class="num">{{ inteiro(totais.litros) }} <i>L</i></b>
    </div>
    <div class="cartao kpi">
      <span class="rot">Gasto total</span>
      <b class="num">R$ {{ moeda(totais.gasto) }}</b>
    </div>
    <div class="cartao kpi" :class="totais.excedente > 0 ? 'k-mau' : 'k-bom'">
      <span class="rot">{{ totais.excedente > 0 ? 'Excedente' : 'Economia' }} sobre a região</span>
      <b class="num">R$ {{ moeda(Math.abs(totais.excedente)) }}</b>
    </div>
  </div>

  <section v-if="pior && melhor" class="cartao leitura surge d2">
    <h3>Leitura do período</h3>
    <p>
      Seu pior mês foi <strong>{{ mesBr(pior.mes) }}</strong>, pagando
      <strong class="acima">{{ pct(pior.diferencaPercentual) }}</strong> em relação à média
      da região; o melhor foi <strong>{{ mesBr(melhor.mes) }}</strong>, com
      <strong :class="melhor.diferencaPercentual > 0 ? 'acima' : 'abaixo'">{{ pct(melhor.diferencaPercentual) }}</strong>.
      Fechar essa diferença no volume do período vale
      <strong class="num">R$
        {{ moeda(Math.abs((pior.diferencaPercentual - melhor.diferencaPercentual) / 100 * totais.gasto)) }}</strong>.
    </p>
  </section>

  <section class="cartao surge d3">
    <div class="cartao-cab">
      <h2>Mês a mês</h2>
      <span class="rot">barra à direita = pagou acima</span>
    </div>
    <div class="tab-rolagem">
      <table class="tab">
        <thead>
          <tr>
            <th>Mês</th>
            <th class="n">Abast.</th>
            <th class="n">Litros</th>
            <th class="n">Gasto</th>
            <th class="n">Pago</th>
            <th class="n">Região</th>
            <th class="col-div">Diferença</th>
            <th class="n">Excedente</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="m in d.relatorio" :key="m.mes">
            <td>{{ mesBr(m.mes) }}</td>
            <td class="n">{{ m.compras }}</td>
            <td class="n">{{ inteiro(m.litros) }}</td>
            <td class="n">{{ moeda(m.valorTotal) }}</td>
            <td class="n">{{ nf(m.precoPago) }}</td>
            <td class="n">{{ nf(m.precoRegiao) }}</td>
            <td class="col-div">
              <span class="div-trilho">
                <i class="eixo-zero"></i>
                <i
                  class="div-b"
                  :class="m.diferencaPercentual > 0 ? 'acima' : 'abaixo'"
                  :style="
                    m.diferencaPercentual > 0
                      ? { left: '50%', width: (Math.abs(m.diferencaPercentual) / maiorDif) * 50 + '%' }
                      : { right: '50%', width: (Math.abs(m.diferencaPercentual) / maiorDif) * 50 + '%' }
                  "
                ></i>
                <b class="div-v num" :class="m.diferencaPercentual > 0 ? 'acima' : 'abaixo'">
                  {{ pct(m.diferencaPercentual) }}
                </b>
              </span>
            </td>
            <td class="n" :class="m.excedente > 0 ? 'mau' : 'bom'">
              {{ moeda(Math.abs(m.excedente)) }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </section>
</template>

<style scoped>
.btn {
  padding: 6px 13px;
  border-radius: var(--r-1);
  border: 1px solid var(--linha-forte);
  background: var(--superficie);
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
}
.btn:hover { background: var(--superficie-2); border-color: var(--marca); color: var(--marca); }

.kpi { padding: 13px 15px; display: flex; flex-direction: column; gap: 5px; }
.kpi b { font-size: 24px; font-weight: 600; letter-spacing: -0.025em; }
.kpi b i { font-style: normal; font-size: 13px; color: var(--tinta-3); font-weight: 500; }
.k-mau b { color: var(--sobe); }
.k-bom b { color: var(--cai); }

.leitura { padding: 15px 17px; margin: 14px 0; }
.leitura h3 { margin-bottom: 6px; }
.leitura p { font-size: 14px; color: var(--tinta-2); line-height: 1.6; max-width: 84ch; }
.leitura strong { color: var(--tinta); font-weight: 600; }
.acima { color: var(--sobe); }
.abaixo { color: var(--cai); }

.col-div { min-width: 170px; }
.div-trilho { position: relative; display: block; height: 20px; }
.eixo-zero { position: absolute; left: 50%; top: 2px; bottom: 2px; width: 1px; background: var(--linha-forte); }
.div-b {
  position: absolute;
  top: 6px;
  height: 8px;
  border-radius: 3px;
  min-width: 2px;
}
.div-b.acima { background: var(--sobe); border-radius: 0 3px 3px 0; }
.div-b.abaixo { background: var(--cai); border-radius: 3px 0 0 3px; }
.div-v {
  position: absolute;
  right: 0;
  top: 1px;
  font-size: 11.5px;
  font-weight: 600;
}
.n.mau { color: var(--sobe); }
.n.bom { color: var(--cai); }
</style>
